steps:
## reservations
  - name: 'gcr.io/cloud-builders/docker'
    args:  [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/sleepr-401716/reservations/production',
      '-f',
      'apps/reservations/Dockerfile',
      '.',
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args:  [
      'push','us-east4-docker.pkg.dev/sleepr-401716/reservations/production',
    ]
    
## auth
  - name: 'gcr.io/cloud-builders/docker'
    args:  [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/sleepr-401716/auth/production',
      '-f',
      'apps/auth/Dockerfile',
      '.',
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args:  [
      'push','us-east4-docker.pkg.dev/sleepr-401716/auth/production',
    ]

## notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:  [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/sleepr-401716/notifications/production',
      '-f',
      'apps/notifications/Dockerfile',
      '.',
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args:  [
      'push','us-east4-docker.pkg.dev/sleepr-401716/notifications/production',
    ]

## payments
  - name: 'gcr.io/cloud-builders/docker'
    args:  [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/sleepr-401716/payments/production',
      '-f',
      'apps/payments/Dockerfile',
      '.',
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args:  [
      'push','us-east4-docker.pkg.dev/sleepr-401716/payments/production',
    ]
                