version: '3.8'
services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    # tty: true
    # command: ["/bin/sh"]
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mysql
  reservations:
    image: reservations
    ports:
      - 3000:3000
    env_file:
      - ../apps/reservations/.env
  auth:
    image: auth
    ports:
      - 3001:3001
    env_file:
      - ../apps/auth/.env      
  payments:
    image: payments
    ports:
      - 3003:3003
    env_file:
      - ../apps/payments/.env     
  notifications:
    image: notifications
    ports:
      - 3004:3004
    env_file:
      - ../apps/notifications/.env   
  mysql:
    image: mysql
    env_file:
      - ../.env
    ports:
      - 3306:3306

        